In [13]:
import numpy as np

my_array=np.array([1,2,3,4])
len(my_array)
my_array.shape

1

In [12]:
print(my_array.ndim)
print(my_array.size)
print(my_array.dtype)

1

In [18]:
print(my_array.size)
print(my_array[2:4])
for e in my_array:
    print(e)

4
[3 4]
1
2
3
4


In [19]:
print(my_array.mean())
print(np.mean(my_array))

2.5
2.5


In [25]:
np.ones(10)
np.ones(10,dtype='int')
np.zeros(10)
np.random.random(10)

array([0.81663325, 0.5775671 , 0.83259225, 0.6151942 , 0.47444463,
       0.78040144, 0.7161867 , 0.26996688, 0.50035081, 0.53353716])

In [21]:
np.dtype(float).itemsize

8

In [26]:
normal_array = np.random.randn(1000)
print("The sample mean and standard devation are %f and %f, respectively." %(np.mean(normal_array), np.std(normal_array)))

The sample mean and standard devation are -0.006630 and 1.008294, respectively.


In [31]:
grid=np.arange(0.,1.01,0.1)
np.random.choice(grid, 5, replace=False)
#np.random.choice(grid, 20, replace=False) asta nu merge ca nu poti sa iei sample mai mare decat population
#cand replace=false
#in schimb merge cand =true
np.random.choice(grid, 20, replace=True)

array([0.6, 0.8, 0.3, 0.9, 0.2, 0.3, 0. , 0.8, 0.1, 0.6, 0.1, 0.8, 0.3,
       0.2, 0.6, 0.8, 0.8, 0.4, 1. , 1. ])

In [32]:
x = np.linspace(-10, 10, 1000) # linspace() returns evenly-spaced numbers over a specified interval
x[-5:], x[:5]

(array([ 9.91991992,  9.93993994,  9.95995996,  9.97997998, 10.        ]),
 array([-10.        ,  -9.97997998,  -9.95995996,  -9.93993994,
         -9.91991992]))